# name: WORKERS - Production Deployment

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: pnpm/action-setup@v3
#         with:
#           version: 8
#       - uses: actions/setup-node@v4
#         with:
#           check-latest: true
#           node-version-file: '.nvmrc'
#           cache: 'pnpm'

#       - name: Install dependencies 🧳
#         run: pnpm install

#       - name: Check Lint 💅🏻
#         run: pnpm lint && pnpm typecheck
 
#       - name: Deploy 🚀
#         run: |
#           pnpm add -g wrangler
#           pnpm api:deploy
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
